@startuml
actor "Aluno" as Aluno
actor "Professor" as Professor

package "Frontend" {
  [Dashboard]
  [Página Inicial]
}

package "Backend" {
  [Serviço de Autenticação]
  [Serviços de Aluno]
  [Serviços de Professor]
  [Serviços de Curso]
}

package "Banco de Dados" {
  [Usuários]
  [Cursos]
}


Aluno --> [Página Inicial] : "Fazer Login/Cadastro"
Professor --> [Página Inicial] : "Fazer Login/Cadastro"
Aluno --> [Dashboard] : "Acessar Dashboard"
Professor --> [Dashboard] : "Acessar Dashboard"

[Página Inicial] --> [Serviço de Autenticação] : "Acessa"
[Serviço de Autenticação] --> [Usuários] : "Acessa"

[Dashboard] --> [Serviços de Professor] : "Acessa"
[Dashboard] --> [Serviços de Aluno] : "Acessa"

[Serviços de Professor] --> [Serviços de Curso]
[Serviços de Aluno] --> [Serviços de Curso]

[Serviços de Curso] --> [Cursos] : "Acessa/Modifica"

@enduml
