@startuml

|Usuário|
start
:Acessa a área de cadastro;

|Sistema|
:Solicita dados do usuário (senha, email, nome, Professor/Aluno, Instituição(Opicional));

|Usuário|
:Informa os dados;

|Sistema|
while (Dados inconsistentes?) is (Sim)
    if (E-mail já cadastrado?) then (Sim)
        :Mensagem de erro - "Email já cadastrado";

        |Usuário|
        :Digita novo Email ou Optou por fazer login;

        |Sistema|
        if ("Optou por fazer login?") then (Sim)
            :Opta por fazer login;
            stop
        else (Não)
        endif
    else (Não)
        :Verifica inconsistencia da instituição;
        stop
    endif

endwhile (Não)

|Sistema|
:Cadastro realizado;
stop

@enduml