# Generated by Django 5.1.4 on 2024-12-10 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_cursos_app', '0002_curso_modulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='site_cursos_app.curso'),
            preserve_default=False,
        ),
    ]
