@startuml

|Usuário|
start
:Acessa a área de login;

|Sistema|
:Solicita dados do usuário (email, senha);

|Usuário|
:Informa os dados;

|Sistema|
while (Dados inconsistentes?) is (Sim)
    :Mensagem: "Email ou Senha inválidos";
    stop
    
endwhile (Não)

|Sistema|
:Acesso ao sistema;
stop

@enduml