
@startuml
actor Usuário

activate Usuário

activate Interface
Usuário -> Interface: Acessa a área de redefinição de senha

Interface --> Usuário: Solicita o email do usuário

Usuário -> Interface: Fornece o email

activate Controlador
Interface -> Controlador: Email

alt Email não encontrado
    Controlador -> Interface: Mensagem: "Email não cadastrado"
    Interface --> Usuário: Mensagem: "Email não cadastrado"

    deactivate Controlador
    loop Enquanto email não encontrado
        Interface -> Usuário: Solicita novo email
        Usuário -> Interface: Fornece novo email

        activate Controlador
        Interface -> Controlador: Email

    end
else Email encontrado
    Controlador -> Interface: Solicita redefinição de senha por email
    Interface --> Usuário: Solicita redefinição de senha por email

    deactivate Controlador
    Usuário -> Interface: Fornece nova senha

    activate Controlador
    Interface -> Controlador: senha
    Controlador -> Interface: Senha redefinida com sucesso
    Interface --> Usuário: Senha redefinida com sucesso

    deactivate Controlador
    Interface -> Usuário: Redireciona para a página de login
end

deactivate Interface
deactivate Usuário
@enduml
