@startuml
actor Usuario
participant "Controller" as C
participant "ServicoAluno" as S
participant "Curso" as Curso
participant "Modulo" as Modulo

activate Usuario
Usuario -> C: Request (POST ou GET)
activate C

group Requisição POST
    C -> C: Obter 'id_usuario' e 'id_curso'
    alt id_usuario ou id_curso é None
        C -> Usuario: Exibir mensagem de erro\nLançar RuntimeError
    else
        C -> S: InscreverCurso(id_usuario, id_curso)
        activate S
        S --> C: Confirmação de inscrição
        deactivate S
        
    end
end

group Requisição GET
    C -> C: Obter 'query'
    alt query não é vazia
        C -> S: GetCursosNome(query)
        activate S
        S --> C: Lista de cursos
        deactivate S

        loop Para cada curso
            C -> Curso: Obter módulos
            activate Curso

            loop Para cada módulo
                C -> Modulo: Exibir nome do módulo
                activate Modulo
                deactivate Modulo
            end

            deactivate Curso
        end
    else
        C -> C: Definir lista de cursos vazia
    end
end

C -> Usuario: Renderizar "course_search.html" com resultados
deactivate C
deactivate Usuario

@enduml
