@startuml teste

skinparam Style strictuml
actor Aluno
actor Professor

Aluno -- (Pesquisar por Curso)
Aluno -- (Acessar Dashboard)

(Acessar Dashboard) ..> (Acessar curso inscrito) :<<extended>>

(Acessar curso inscrito) .> (Acessar Aulas) :<<extended>>
(Acessar curso inscrito) ..> (Concluir Curso) :<<extended>>

(Acessar Aulas) ..> (Baixar Materiais) :<<extended>>
(Acessar Aulas) ..> (Concluir a aula) :<<extended>>
(Concluir Curso)  .> (Gerar Certificado) :<<extended>>

(Pesquisar por Curso) ..> (Ver Curso) :<<extended>>
(Ver Curso) ..> (Inscrever no curso) :<<extended>>

Professor -- (Pesquisar por Curso)
Professor -- (Gerir seus Cursos)

Professor -- (Acessar Dashboard) 
(Gerir seus Cursos) ..> (Criar Curso) :<<extended>>
(Gerir seus Cursos) ..> (Editar Curso Existente) :<<extended>>
(Criar Curso) ..> (Gerenciar Mídia e Materiais) :<<extended>>

@enduml